### PR TITLE
Use latest test unit

### PR DESCRIPTION
**Pull request by okkez**
Pass all tests in my local.

### CODE REVIEW

**Comment by kiyoto** [comment]
Thanks! At this point, do you want to take over the repo, @okkez? Happy to have you maintain it.

**Comment by okkez** [comment]
@kiyoto Thank you for merging my PRs.

I don't want to take over this repo. But I can co-maintain this.

I think fluent organization is better for this plugin.
This is good example for parser plugin.

**Comment by kiyoto** [comment]
Got it.

1. Adding you as a co-maintainer right now.
2. Will talk to the Fluentd core team and see if they want to absorb this.
3. Closing #11, since you already answered here.

**Comment by okkez** [comment]
Sounds good.
Go ahead, please.

**Comment by cosmo0920** [comment]
BTW, this Travis CI settings is actually used in Travis? @okkez 
I couldn't find any executed job in Travis: https://travis-ci.org/kiyoto/fluent-plugin-grok-parser/builds

**Comment by okkez** [comment]
See also #15

**Comment by cosmo0920** [comment]
Ah, I got it, thanks.

**Pull request merged**
