### PR TITLE
Support multiline

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
There are some problems in this implementation.

* `%{GREEDYDATA}` does not much multiline
  * so test is failed, for now.
* In `parse(text)`, `text` does not include line break.
  * Maybe this line break is deleted by fluentd automatically.
  * Should we append line break?
* This plugin cannot process last record forever
  * How to detect the end of last record?

Request for comments, please.
Thanks.

**Comment by okkez** [comment]
This is for #6

**Comment by visualphoenix** [comment]
maybe it can buffer until an end regex is matched or until the start regex matches again? Obviously this would not work for multiple workers (same problem as multiline in logstash)

**Comment by visualphoenix** [comment]
could also possibly flush out after a timeout

**Comment by visualphoenix** [comment]
for parser problem maybe check how they did multilinecsv? https://github.com/fluent/fluentd/pull/543/files

**Comment by okkez** [comment]
Thank you for your comment!

> maybe it can buffer until an end regex is matched or until the start regex matches again? 

Yes, I think so, too.

> could also possibly flush out after a timeout

Maybe, this is fluentd's in_tail plugin's issue.
I will check fluentd's in_tail plugin codes.

**Comment by okkez** [comment]
Rebased.
I added a feature to parse multiline log that we can suppose the format.

**Comment by okkez** [comment]
@visualphoenix How about 9f3b25f and db49d34?

**Comment by visualphoenix** [comment]
Looks good to me. We can invent new refinements as we use it more.

On Monday, November 16, 2015, okkez <notifications@github.com> wrote:

> @visualphoenix <https://github.com/visualphoenix> How about 9f3b25f
> <https://github.com/kiyoto/fluent-plugin-grok-parser/commit/9f3b25fbb89e7e18c2f1562127bd81b2f4503607>
> and db49d34
> <https://github.com/kiyoto/fluent-plugin-grok-parser/commit/db49d34c2dca611577242830d2ebec9103a21890>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiyoto/fluent-plugin-grok-parser/pull/10#issuecomment-156962859>
> .
>


-- 
Raymond "VisualPhoenix" Barbiero

**Comment by okkez** [comment]
Thanks merged.

**Pull request merged**
